_wandb:
    value:
        cli_version: 0.21.0
        e:
            1hqnilw7j1ds4lpvru2cd9ox9uv8lbjg:
                args:
                    - src.main:app
                    - --host
                    - 0.0.0.0
                    - --port
                    - "8001"
                    - --reload
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "498684919808"
                        used: "286374572032"
                email: elliotttmiller@hotmail.com
                executable: C:\Users\AMD\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 7ff0ff9be791376202bcbd5c30b10effa70a02fd
                    remote: https://github.com/elliotttmiller/sentinel.ai.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-ceb7970b-f836-81d2-c126-25b8b7e0da61
                host: DESKTOP-7CFR9JU
                memory:
                    total: "17101807616"
                os: Windows-10-10.0.26100-SP0
                program: <python with no main file>
                python: CPython 3.11.9
                root: C:\Users\AMD\sentinel\desktop-app
                startedAt: "2025-08-02T03:42:12.761184Z"
                writerId: 1hqnilw7j1ds4lpvru2cd9ox9uv8lbjg
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 49
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "2":
                - 49
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "3":
                - 16
            "4": 3.11.9
            "5": 0.21.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.0
            "13": windows-amd64
system_version:
    value: v5.1
