_wandb:
    value:
        cli_version: 0.21.0
        e:
            11fh7ullf89cizlx8xzlqj7wxsmu956m:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "498684919808"
                        used: "286042775552"
                email: elliotttmiller@hotmail.com
                executable: C:\Users\AMD\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 9c0d40499bd37038f7097250be9ce0c86b412bb6
                    remote: https://github.com/elliotttmiller/sentinel.ai.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-ceb7970b-f836-81d2-c126-25b8b7e0da61
                host: DESKTOP-7CFR9JU
                memory:
                    total: "17101807616"
                os: Windows-10-10.0.26100-SP0
                program: <python with no main file>
                python: CPython 3.11.9
                root: C:\Users\AMD\sentinel\desktop-app
                startedAt: "2025-08-02T20:07:11.660587Z"
                writerId: 11fh7ullf89cizlx8xzlqj7wxsmu956m
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 95
                - 96
                - 97
                - 105
            "2":
                - 95
                - 96
                - 97
                - 105
            "3":
                - 13
            "4": 3.11.9
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
