_wandb:
    value:
        cli_version: 0.21.0
        e:
            0b6hxt57nrkwznw6u7xj6ndioz7bhvym:
                args:
                    - src.main:app
                    - --host
                    - 0.0.0.0
                    - --port
                    - "8001"
                    - --reload
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "498684919808"
                        used: "286444511232"
                email: elliotttmiller@hotmail.com
                executable: C:\Users\AMD\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 6eb364f6a1fa76c07cf746f6e9ae634412fa7706
                    remote: https://github.com/elliotttmiller/sentinel.ai.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-ceb7970b-f836-81d2-c126-25b8b7e0da61
                host: DESKTOP-7CFR9JU
                memory:
                    total: "17101807616"
                os: Windows-10-10.0.26100-SP0
                program: <python with no main file>
                python: CPython 3.11.9
                root: C:\Users\AMD\sentinel\desktop-app
                startedAt: "2025-08-03T00:38:21.448468Z"
                writerId: 0b6hxt57nrkwznw6u7xj6ndioz7bhvym
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 95
                - 96
                - 97
                - 105
            "2":
                - 92
                - 95
                - 96
                - 97
                - 105
            "4": 3.11.9
            "5": 0.21.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.0
            "13": windows-amd64
