_wandb:
    value:
        cli_version: 0.21.0
        e:
            273v9v2d4lnonu8x5lonqbq9468txckn:
                codePath: desktop-app\system_optimization_hub.py
                codePathLocal: system_optimization_hub.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "498684919808"
                        used: "283859783680"
                email: elliotttmiller@hotmail.com
                executable: C:\Users\AMD\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 538aced9009eae67278451ede767b838fbddb9c5
                    remote: https://github.com/elliotttmiller/sentinel.ai.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-ceb7970b-f836-81d2-c126-25b8b7e0da61
                host: DESKTOP-7CFR9JU
                memory:
                    total: "17101807616"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\AMD\sentinel\desktop-app\system_optimization_hub.py
                python: CPython 3.11.9
                root: C:\Users\AMD\sentinel\desktop-app
                startedAt: "2025-07-31T19:05:31.500877Z"
                writerId: 273v9v2d4lnonu8x5lonqbq9468txckn
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 49
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "2":
                - 49
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "3":
                - 16
            "4": 3.11.9
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
observability_enabled:
    value: true
system_version:
    value: v5.0
weave_integration:
    value: true
