_wandb:
    value:
        cli_version: 0.21.0
        e:
            6b4zmbkrctd3jjvacb4h5r2mk6g0snuf:
                codePath: test_real_agent_execution.py
                codePathLocal: test_real_agent_execution.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "498684919808"
                        used: "297493209088"
                email: elliotttmiller@hotmail.com
                executable: C:\Users\AMD\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: e3ea53385f58e8c29f671501f476ab92eba1dc26
                    remote: https://github.com/elliotttmiller/sentinel.ai.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-ceb7970b-f836-81d2-c126-25b8b7e0da61
                host: DESKTOP-7CFR9JU
                memory:
                    total: "17101807616"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\AMD\sentinel\test_real_agent_execution.py
                python: CPython 3.11.9
                root: C:\Users\AMD\sentinel
                startedAt: "2025-08-05T15:06:06.709616Z"
                writerId: 6b4zmbkrctd3jjvacb4h5r2mk6g0snuf
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "2":
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "4": 3.11.9
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
