_wandb:
    value:
        cli_version: 0.21.0
        e:
            s56sanjppwqcl4fghrunzzja2em7806v:
                codePath: desktop-app\src\main.py
                codePathLocal: desktop-app\src\main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "498684919808"
                        used: "297039175680"
                email: elliotttmiller@hotmail.com
                executable: C:\Users\AMD\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: b9b370fbcb9f0638573baceb75debcafb3cfb6df
                    remote: https://github.com/elliotttmiller/sentinel.ai.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-ceb7970b-f836-81d2-c126-25b8b7e0da61
                host: DESKTOP-7CFR9JU
                memory:
                    total: "17101807616"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\AMD\sentinel\desktop-app\src\main.py
                python: CPython 3.11.9
                root: C:\Users\AMD\sentinel
                startedAt: "2025-08-05T12:51:08.034982Z"
                writerId: s56sanjppwqcl4fghrunzzja2em7806v
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 92
                - 95
                - 96
                - 97
                - 105
            "2":
                - 49
                - 86
                - 92
                - 95
                - 96
                - 97
                - 105
            "4": 3.11.9
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
